name: tests
on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
    
      - run: go version

      - name: Run go vet
        run: go vet ./...
    
      - name: Run go test
        run: go test -v -race -coverprofile coverage.txt -covermode atomic ./... && go tool cover -html=coverage.txt -o coverage.html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1